### ISSUE TITLE
convention 및 branch naming 

### ISSUE THREAD

**Issue by lielocks** [134talk/backend#2]
# 🔨branch
<body>

### -branch는 main / dev / feature로 진행합니다.
```
main
⌙ dev
⌙ feature/login ⌙ feature/filter //구현하는 기능에 따라 생성됩니다.
```

`feature/[기능]`의 형태로 기능별 브랜치를 생성해 작업 후 ➡️
 `dev`에서 합친 이후에 ➡️
최종적으로 `main`에 pr하여 merge 합니다.
### -branch naming
feature/기능요약 형식을 추천합니다. ex) feature/login

-feature/{issue-number}-{feature-name} 이슈추적을 사용하여 이와 같은 형식을 따릅니다.
ex) feature/#1-init-project, refactor/#2-login-filter

</body>
</br></br>

# ➕pull request & merge
<body>

### -pr시 reviewers엔 두명을 추가합니다. 
최소 1명 이상의 approve를 받으면 머지가 가능합니다.

### -pr의 reviewers로 배정된 팀원은 응답을 합니다.
코드에 **코멘트를 달거나(Comment)**,
**수정요청을하거나(Request changes)**, 
이 두가지 모두 별다른게 없다면, **승인을 하여(Approve)** merge할 수 있도록 해줍니다.

### -merge한 후, 필요없어진 branch는 제거해 줍니다.

</body>
</br></br>

**Comment by jhkim593** [comment]
확인했습니다!
